name: react-native-android-build
on: workflow_dispatch
jobs:
  build:
    name: Install and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 4.x
          expo-username: username
          expo-password: pass
          expo-cache: true
      - run: yarn install
      - run: expo build:android -t apk
      - run: expo build:android -t app-bundle
